name: My first workflow

on: push

jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps: 
        - name: checkout repo 
          uses: actions/checkout@v4 

        - name: List and Read files
          run: |
               echo "my first github actiom"
               ls -ltr
               cat README.md

        - name: generate ascii artwork
          run: cowsay -f dragon " run forcover, i'm a dragon" >> dragon.txt

        # - name: list files
        #   run: ls

        # - name: read file
        #   run: cat README.md
          